spring:
  application:
    name: toughjet-api
  datasource:
    url: jdbc:postgresql://localhost:5434/toughjet-db
    username: toughjet-user
    password: this1isNotGood!

app:
  percentage:
    discount: 5
    tax: 15

server:
  port: 8082
